[project]
name = "ocr-evaluate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "levenshtein>=0.27.1",
    "nltk>=3.9.1",
    "numpy>=2.2.4",
]
